# Generated by Django 3.1.3 on 2020-12-01 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20201201_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menu'),
        ),
    ]
