# Generated by Django 3.1.3 on 2020-12-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_order_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='list',
            new_name='meal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='order',
            name='waiter',
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.table'),
        ),
    ]
