# Generated by Django 3.1.3 on 2020-12-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20201201_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_types',
            field=models.CharField(choices=[('pizza', 'pizza'), ('soups', 'soups'), ('bbq', 'bbq'), ('burgers', 'burgers'), ('noodles', 'noodles'), ('drinks', 'drinks')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.waiter'),
        ),
    ]
