# Generated by Django 3.1.3 on 2020-12-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20201201_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waiter',
            name='name',
        ),
    ]
