# Generated by Django 3.1.3 on 2020-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_waiter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiter',
            name='waiter',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
