# Generated by Django 3.1.3 on 2020-12-03 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20201202_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.sales'),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.order'),
        ),
    ]
