# Generated by Django 3.1.3 on 2020-12-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20201203_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutoorder',
            name='ammounts',
            field=models.IntegerField(default=0),
        ),
    ]
