# Generated by Django 3.1.3 on 2020-12-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_menutoorder_ammounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutoorder',
            old_name='ammounts',
            new_name='amounts',
        ),
    ]
