# Generated by Django 3.1.3 on 2020-12-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_auto_20201203_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sale',
        ),
        migrations.AddField(
            model_name='menutoorder',
            name='percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menutoorder',
            name='sales',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
