# Generated by Django 3.1.3 on 2020-12-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_auto_20201203_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutoorder',
            name='sales',
        ),
    ]
