# Generated by Django 3.1.3 on 2020-12-04 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.order'),
        ),
    ]
