# Generated by Django 3.1.3 on 2020-12-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_auto_20201208_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutoorder',
            name='sales',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.order'),
        ),
    ]
